<?php
/*
 * Alle Adressen der Seite. Handler: "datei:funktion", die Datei liegt unter
 * .htapp und wird erst geladen, wenn ihre Route passt. Reihenfolge zaehlt:
 * feste Pfade vor Mustern mit {id}.
 */

declare(strict_types=1);

return [
    // Seiten
    ['GET', '/', 'pages/welcome:page_welcome'],
    ['GET', '/account', 'pages/account:page_account'],
    ['POST', '/account/login', 'pages/account:action_login'],
    ['POST', '/account/register', 'pages/account:action_register'],
    ['POST', '/account/reset', 'pages/account:action_reset'],
    ['POST', '/account/new-password', 'pages/account:action_new_password'],
    ['POST', '/account/logout', 'pages/account:action_logout'],
    ['GET', '/confirm', 'pages/account:page_confirm'],
    ['GET', '/reset', 'pages/account:page_reset'],
    ['GET', '/invite', 'pages/account:page_invite'],
    ['GET', '/device', 'pages/device:page_device'],
    ['GET', '/device/{id}', 'pages/device:page_device'],
    ['GET', '/settings/export', 'pages/settings:download_export'],
    ['GET', '/settings', 'pages/settings:page_settings'],
    ['GET', '/settings/{id}', 'pages/settings:page_settings'],
    ['GET', '/admin', 'pages/admin:page_admin'],
    ['GET', '/legal', 'pages/legal:page_legal'],
    ['GET', '/map', 'pages/map:page_map'],
    ['GET', '/map/stops', 'pages/map:page_map_stops'],
    ['GET', '/animations', 'pages/library:page_animations'],
    ['POST', '/spotify/connect', 'pages/spotify:action_spotify_connect'],
    ['GET', '/spotify/callback', 'pages/spotify:page_spotify_callback'],
    ['GET', '/controls', 'pages/library:page_controls'],

    // JSON fuer den Browser, mit Sitzung
    ['POST', '/api/preview/{id}', 'api/web:api_preview'],
    ['POST', '/api/device/{id}/apply', 'api/web:api_apply'],
    ['POST', '/api/device/{id}/note/hide', 'api/web:api_note_hide'],
    ['POST', '/api/device/{id}/timer', 'api/web:api_timer_start'],
    ['POST', '/api/device/{id}/timer/cancel', 'api/web:api_timer_cancel'],
    ['POST', '/api/device/{id}/ring/stop', 'api/web:api_ring_stop'],
    ['POST', '/api/device/{id}/alarm', 'api/web:api_alarm_save'],
    ['POST', '/api/device/{id}/ha/unlink', 'api/web:api_ha_unlink'],
    ['POST', '/api/device/{id}/settings', 'api/web:api_device_settings'],
    ['POST', '/api/device/{id}/update', 'api/web:api_device_update'],
    ['POST', '/api/device/{id}/remove', 'api/web:api_device_remove'],
    ['POST', '/api/device/{id}/invite', 'api/web:api_share_invite'],
    ['POST', '/api/device/{id}/rights', 'api/web:api_share_rights'],
    ['POST', '/api/device/{id}/unshare', 'api/web:api_share_remove'],
    ['GET', '/api/device/{id}/status', 'api/web:api_device_status'],
    ['GET', '/api/devices', 'api/web:api_devices'],
    ['GET', '/api/logo/{code}', 'api/web:api_logo'],
    ['POST', '/api/geo', 'api/web:api_geo'],
    ['POST', '/api/map/aircraft', 'api/web:api_map_aircraft'],
    ['POST', '/api/transit/stops', 'api/web:api_transit_stops'],
    ['POST', '/api/transit/all', 'api/web:api_transit_all'],
    ['POST', '/api/transit/stop', 'api/web:api_transit_stop'],
    ['POST', '/api/account/key', 'api/web:api_rotate_key'],
    ['POST', '/api/account/password', 'api/web:api_change_password'],
    ['POST', '/api/account/export-mail', 'api/web:api_export_mail'],
    ['POST', '/api/account/delete', 'api/web:api_delete_account'],
    ['POST', '/api/account/tour', 'api/web:api_tour_seen'],
    ['GET', '/api/device/{id}/spotify', 'api/web:api_spotify_status'],
    ['POST', '/api/spotify/disconnect', 'api/web:api_spotify_disconnect'],
    ['POST', '/api/admin/registration', 'api/admin:api_registration'],
    ['POST', '/api/admin/signup-link', 'api/admin:api_signup_link'],
    ['POST', '/api/admin/firmware', 'api/admin:api_firmware'],
    ['POST', '/api/admin/firmware-upload', 'api/admin:api_firmware_upload'],
    ['POST', '/api/admin/smtp', 'api/admin:api_smtp'],
    ['POST', '/api/admin/smtp-test', 'api/admin:api_smtp_test'],
    ['POST', '/api/admin/imprint', 'api/admin:api_imprint'],
    ['POST', '/api/admin/test-device', 'api/admin:api_test_device'],
    ['POST', '/api/admin/spotify', 'api/admin:api_spotify'],
    ['POST', '/api/admin/spotify-test', 'api/admin:api_spotify_test'],
    ['POST', '/api/admin/transit', 'api/admin:api_transit'],
    ['POST', '/api/admin/transit-test', 'api/admin:api_transit_test'],
    ['POST', '/api/admin/transit-sample', 'api/admin:api_transit_sample'],
    ['POST', '/api/admin/transit-raw', 'api/admin:api_transit_raw'],

    // Geraete-API, mit API-Schluessel
    ['GET', '/api/v1/frame', 'api/device:api_frame'],
    ['GET', '/api/v1/rev', 'api/device:api_device_rev'],
    ['GET', '/api/v1/logo/{code}', 'api/device:api_device_logo'],
    ['GET', '/api/v1/firmware/{version}', 'api/device:api_firmware_download'],
    ['POST', '/api/v1/ring/stop', 'api/device:api_device_ring_stop'],

    // Home Assistant, gekoppelt mit einem Code vom Panel, danach mit eigenem Schluessel
    ['POST', '/api/ha/v1/pair', 'api/ha:ha_api_pair'],
    ['POST', '/api/ha/v1/pair/confirm', 'api/ha:ha_api_pair_confirm'],
    ['GET', '/api/ha/v1/state', 'api/ha:ha_api_state'],
    ['POST', '/api/ha/v1/panel', 'api/ha:ha_api_panel'],
    ['POST', '/api/ha/v1/note', 'api/ha:ha_api_note'],
    ['POST', '/api/ha/v1/note/hide', 'api/ha:ha_api_note_hide'],
    ['POST', '/api/ha/v1/timer', 'api/ha:ha_api_timer'],
    ['POST', '/api/ha/v1/timer/cancel', 'api/ha:ha_api_timer_cancel'],
    ['POST', '/api/ha/v1/alarm', 'api/ha:ha_api_alarm'],
    ['POST', '/api/ha/v1/ring/stop', 'api/ha:ha_api_ring_stop'],
    ['POST', '/api/ha/v1/firmware/update', 'api/ha:ha_api_firmware_update'],
    ['POST', '/api/ha/v1/unlink', 'api/ha:ha_api_unlink'],
];
